version: '3.8'

services:
  carefreepass:
    build: .
    container_name: carefreepass-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=datasource
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs