spring:
  application:
    name: CareFreePass-Server
  profiles:
    group:
      local: "local, datasource"
      dev: "dev, datasource"

    include:
      - redis
      - firebase
      - security

swagger:
  version: ${SWAGGER_VERSION:0.0.1}
  url: ${SWAGGER_URL:http://localhost:8080}
