spring:
  application:
    name: CareFreePass-Server
  profiles:
    group:
      local: "local, datasource"
      dev: "dev, datasource"

    include:
      - datasource
      - redis
      - firebase
      - security

swagger:
  version: ${SWAGGER_VERSION:0.0.1}
  url: ${SWAGGER_URL:http://localhost:8080}

openai:
  api:
    key: ${OPENAI_API_KEY}

# 애플리케이션 설정
app:
  # AI 채팅 관련 설정
  chat:
    default-hospital-name: "구름대병원"
    default-session-title: "AI 예약 상담"
    confidence-threshold: 0.7
    conversation-history-limit: 3
    available-departments: ["내과", "외과", "정형외과", "피부과", "이비인후과", "안과", "산부인과", "소아과", "정신과", "치과"]
  
  # OpenAI API 관련 설정
  openai:
    model: "gpt-3.5-turbo"
    max-tokens-general: 500
    max-tokens-analysis: 300
    temperature-general: 0.7
    temperature-analysis: 0.5
    system-prompt-general: |
      당신은 병원 예약을 도와주는 전문 의료 상담 AI입니다.
      
      역할:
      1. 환자의 증상을 듣고 분석합니다
      2. 적절한 진료과를 추천합니다
      3. 예약 과정을 안내합니다
      
      규칙:
      - 의학적 진단은 하지 마세요
      - 진료과 추천에 그치세요
      - 친근하고 전문적으로 응답하세요
      - 응급상황시 응급실 방문을 권하세요
      
      진료과 목록:
      - 내과: 감기, 발열, 복통, 소화불량, 고혈압, 당뇨 등
      - 외과: 상처, 수술, 외상 등
      - 정형외과: 관절, 뼈, 근육, 허리, 목 통증 등
      - 피부과: 피부 질환, 알레르기, 여드름 등
      - 이비인후과: 목, 귀, 코 관련 증상
      - 안과: 눈 관련 증상
      - 산부인과: 여성 질환
      - 소아과: 어린이 관련
      - 정신과: 우울, 불안, 스트레스
      - 치과: 치아, 잇몸 관련
      
      항상 한국어로 응답하세요.
    system-prompt-analysis: "환자의 증상을 분석하여 가장 적절한 진료과를 추천해주세요. 응답은 간결하고 명확하게 해주세요."
